#!/usr/bin/env bash
# builds .github/CODEOWNERS from each recipe's maintainer= (a GitHub username)
# → PRs touching a package automatically ask its maintainer to review
set -euo pipefail
cd "$(dirname "$0")/.."
OWNER="${GURT_OWNER:-clrealy}"
{
  echo "# generated by tools/gen-codeowners.sh from each GURTBUILD's maintainer= — don't edit by hand"
  echo "*  @$OWNER"
  for d in packages/*/; do
    n=$(basename "$d")
    m=$(awk -F' = ' '$1 == "maintainer" {print $2; exit}' "$d/.gurtinfo" 2>/dev/null || true)
    m=${m#@}
    if [[ $m =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,38})$ ]]; then
      if [[ ${m,,} == "${OWNER,,}" ]]; then echo "/packages/$n/  @$OWNER"
      else echo "/packages/$n/  @$m @$OWNER"; fi
    fi
  done
} > .github/CODEOWNERS
echo "wrote .github/CODEOWNERS ($(grep -c '^/packages' .github/CODEOWNERS) packages)"
